alg:
  algorithm: 'DQN'
  policy: 'CnnPolicy'
  tensorboard_log: '../runs'
  verbose: 1
  seed: 42
  device: 'cuda' 

PPO:
  learning_rate: 0.0001
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  rollout_buffer_class: null
  rollout_buffer_kwargs: null
  target_kl: null
  stats_window_size: 100
  policy_kwargs: null

DQN:
  learning_rate: 0.00001
  buffer_size: 10000
  learning_starts: 1000
  batch_size: 64
  tau: 0.99
  gamma: 0.99
  train_freq: 10
  gradient_steps: 1
  replay_buffer_class: null
  replay_buffer_kwargs: null
  optimize_memory_usage: false
  target_update_interval: 10000
  exploration_fraction: 0.2
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.2
  max_grad_norm: 10
  stats_window_size: 100
  policy_kwargs: null

A2C:
  learning_rate: 0.0003
  n_steps: 1000
  gamma: 0.99
  gae_lambda: 1.0
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  rms_prop_eps: 0.00001
  use_rms_prop: true
  use_sde: false
  sde_sample_freq: -1
  rollout_buffer_class: null
  rollout_buffer_kwargs: null
  normalize_advantage: false
  stats_window_size: 100
  policy_kwargs: null


