alg:
  algorithm: 'DQN'
  policy: 'CnnPolicy'
  tensorboard_log: '../runs'
  verbose: 1
  seed: 42
  device: 'cuda' 

PPO:
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  rollout_buffer_class: null
  rollout_buffer_kwargs: null
  target_kl: null
  stats_window_size: 100

DQN:
  learning_rate: 0.0001
  buffer_size: 100000
  learning_starts: 100
  batch_size: 32
  tau: 1.0
  gamma: 0.99
  train_freq: 4
  gradient_steps: 1
  replay_buffer_class: null
  replay_buffer_kwargs: null
  optimize_memory_usage: false
  target_update_interval: 10000
  exploration_fraction: 0.1
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.3
  max_grad_norm: 10
  stats_window_size: 100
  policy_kwargs: null

A2C:
  learning_rate: 0.0007
  n_steps: 5
  gamma: 0.99
  gae_lambda: 1.0
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  rms_prop_eps: 1e-05
  use_rms_prop: true
  use_sde: false
  sde_sample_freq: -1
  rollout_buffer_class: null
  rollout_buffer_kwargs: null
  normalize_advantage: false
  stats_window_size: 100
  policy_kwargs: null

SAC:
  learning_rate: 0.0003
  buffer_size: 100000
  learning_starts: 100
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  action_noise: null
  replay_buffer_class: null
  replay_buffer_kwargs: null
  optimize_memory_usage: false
  ent_coef: 'auto'
  target_update_interval: 1
  target_entropy: 'auto'
  use_sde: false
  sde_sample_freq: -1
  use_sde_at_warmup: false
  stats_window_size: 100
  policy_kwargs: null


